version: '3.7'
volumes:
  data:
  config:
services:
  mysql:
    image: mysql:8.0.20 
    volumes:
      - data:/var/lib/mysql
    environment:
     - MYSQL_ROOT_PASSWORD=root
     - MYSQL_DATABASE=app_development
    restart: always
    ports:
     - 3306:3306
    container_name: mysql 
    networks:
     - backendMysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5
    links:
      - mysql
    ports:
      - 8087:80
    environment:
      - PMA_ARBITRARY=1
    volumes:
    - config:/etc/phpmyadmin/config.user.inc.php
    container_name: phpmyadmin 
    networks:
     - backendMysql

networks:
 backendMysql:
  driver: bridge
  name: backendMysql
 
